version: "3"
services:

  redaxo:
    image: friendsofredaxo/redaxo:5
    ports:
      - 80:80   # web server will use port 80 for http
    volumes:
      - ./html:/var/www/html:cached   # sync web root with local folder `html`
    depends_on:
      - db   # requires database container to be available
    environment:
      REDAXO_SERVER: http://localhost
      REDAXO_SERVERNAME: My Project
      REDAXO_ERROR_EMAIL: mail@you.example
      REDAXO_LANG: de_de
      REDAXO_TIMEZONE: Europe/London
      REDAXO_DB_HOST: db   # database container name
      REDAXO_DB_NAME: redaxo
      REDAXO_DB_LOGIN: redaxo
      REDAXO_DB_PASSWORD: redaxo   # better not use for production!
      REDAXO_DB_CHARSET: utf8mb4
      REDAXO_ADMIN_USER: admin
      REDAXO_ADMIN_PASSWORD: admin123   # better not use for production!

  db:
    image: mysql:8
    volumes:
      - ./db:/var/lib/mysql:cached   # sync database with local folder `db`
    environment:
      MYSQL_DATABASE: redaxo
      MYSQL_USER: redaxo
      MYSQL_PASSWORD: redaxo   # better not use for production!
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'   # better not use for production!

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_USER: redaxo
      PMA_PASSWORD: redaxo
      UPLOAD_LIMIT: 256M
