redaxo:
  - '5.15':
      package-url: https://github.com/redaxo/redaxo/releases/download/5.15.0/redaxo_5.15.0.zip;
      package-sha: ffa10aaab01ffc39425ec31e15c00ec96d948db9
      use-with-php-version-tag: '8.2'
      use-with-mysql-docker-image: 'mariadb:10.11'
      install-redaxo-via-cli: true
  - '5.14':
      package-url: https://github.com/redaxo/redaxo/releases/download/5.14.3/redaxo_5.14.3.zip;
      package-sha: cee366bf49ab4dc653c67722e461bfe9f057a7f3
      use-with-php-version-tag: '7.4'
      use-with-mysql-docker-image: 'mariadb:10.6'
      install-redaxo-via-cli: true
  - '5.13':
      package-url: https://github.com/redaxo/redaxo/releases/download/5.13.3/redaxo_5.13.3.zip;
      package-sha: 0f84089bc8e1b77fbe30d718d41385fd4b177e3a
      use-with-php-version-tag: '7.4'
      use-with-mysql-docker-image: 'mariadb:10.6'
      install-redaxo-via-cli: true
  - '5.12':
      package-url: https://github.com/redaxo/redaxo/releases/download/5.12.1/redaxo_5.12.1.zip;
      package-sha: 2b7fb28820222726fc8b8a06408aa038ff95cb64
      use-with-php-version-tag: '7.4'
      use-with-mysql-docker-image: 'mariadb:10.6'
      install-redaxo-via-cli: true
  - '5.11':
      package-url: https://github.com/redaxo/redaxo/releases/download/5.11.2/redaxo_5.11.2.zip;
      package-sha: 44fca196316606b1a64ba34f873bfc886d3cbbb5
      use-with-php-version-tag: '7.4'
      use-with-mysql-docker-image: 'mariadb:10.6'
      install-redaxo-via-cli: true
  - '5.10':
      package-url: https://github.com/redaxo/redaxo/releases/download/5.10.1/redaxo_5.10.1.zip;
      package-sha: 986c905aec77dfd67b0dbca17aa57505889329b3
      use-with-php-version-tag: '7.4'
      use-with-mysql-docker-image: 'mariadb:10.6'
      install-redaxo-via-cli: true
  - '5.9':
      package-url: https://github.com/redaxo/redaxo/releases/download/5.9.0/redaxo_5.9.0.zip;
      package-sha: 9d8252adeaf17725d317fc5aa5602529df3fc2e6
      use-with-php-version-tag: '7.4'
      use-with-mysql-docker-image: 'mariadb:10.6'
      install-redaxo-via-cli: true
  - '5.8':
      package-url: https://github.com/redaxo/redaxo/releases/download/5.8.1/redaxo_5.8.1.zip;
      package-sha: 4f5175cdb55226e4f3fd8a34688e4199c9731062
      use-with-php-version-tag: '7.4'
      use-with-mysql-docker-image: 'mariadb:10.6'
      install-redaxo-via-cli: false
  - '5.7':
      package-url: https://github.com/redaxo/redaxo/releases/download/5.7.1/redaxo_5.7.1.zip;
      package-sha: ca44f94360861282f4637ca70b2a7a57d0cc32c5
      use-with-php-version-tag: '5.6'
      use-with-mysql-docker-image: 'mariadb:10.3'
      install-redaxo-via-cli: false
  - '5.6':
      package-url: https://github.com/redaxo/redaxo/releases/download/5.6.5/redaxo_5.6.5.zip;
      package-sha: ef05d9c4d27abe65d332a0c86a5662f6cfa2b9bb
      use-with-php-version-tag: '5.6'
      use-with-mysql-docker-image: 'mariadb:10.3'
      install-redaxo-via-cli: false
  - '5.5':
      package-url: https://github.com/redaxo/redaxo/releases/download/5.5.1/redaxo_5.5.1.zip;
      package-sha: 050aa51821531238ffbb084936649cde83026ca4
      use-with-php-version-tag: '5.6'
      use-with-mysql-docker-image: 'mariadb:10.3'
      install-redaxo-via-cli: false
  - '5.4':
      package-url: https://github.com/redaxo/redaxo/releases/download/5.4.0/redaxo_5.4.0.zip;
      package-sha: bdf19a343d91bb23ff5f8a7644af54c643bebd2b
      use-with-php-version-tag: '5.6'
      use-with-mysql-docker-image: 'mariadb:10.3'
      install-redaxo-via-cli: false
  - '5.3':
      package-url: https://github.com/redaxo/redaxo/releases/download/5.3.0/redaxo_5.3.0.zip;
      package-sha: fd20820ab4c1faa905dabe7bb526c3aec8afe24b
      use-with-php-version-tag: '5.6'
      use-with-mysql-docker-image: 'mariadb:10.3'
      install-redaxo-via-cli: false
  - '5.2':
      package-url: https://github.com/redaxo/redaxo/releases/download/5.2.0/redaxo_5.2.0.zip;
      package-sha: fa141b1b7116c5a1349c63193c230d517c112b8e
      use-with-php-version-tag: '5.6'
      use-with-mysql-docker-image: 'mariadb:10.3'
      install-redaxo-via-cli: false
  - '5.1':
      package-url: https://github.com/redaxo/redaxo/releases/download/5.1.0/redaxo_5.1.0.zip;
      package-sha: d9cd7583eb61fd00e3bc91148648a4126245d040
      use-with-php-version-tag: '5.6'
      use-with-mysql-docker-image: 'mariadb:10.3'
      install-redaxo-via-cli: false
  - '5.0':
      package-url: https://github.com/redaxo/redaxo/releases/download/5.0.1/redaxo_5.0.1.zip;
      package-sha: 63eeb763528c68cd3d44bdfa341f1a06ceaf4f41
      use-with-php-version-tag: '5.6'
      use-with-mysql-docker-image: 'mariadb:10.3'
      install-redaxo-via-cli: false

php:
  - '8.2':
      php-version-tag: '8.2'
      use-with-redaxo-version-tag: '5.15'
  - '8.1':
      php-version-tag: '8.1'
      use-with-redaxo-version-tag: '5.15'
  - '8.0':
      php-version-tag: '8.0'
      use-with-redaxo-version-tag: '5.14'
  - '7.4':
      php-version-tag: '7.4'
      use-with-redaxo-version-tag: '5.14'
  - '7.3':
      php-version-tag: '7.3'
      use-with-redaxo-version-tag: '5.14'
  - '7.2':
      php-version-tag: '7.2'
      use-with-redaxo-version-tag: '5.11'
  - '7.1':
      php-version-tag: '7.1'
      use-with-redaxo-version-tag: '5.11'
  - '7.0':
      php-version-tag: '7.0'
      use-with-redaxo-version-tag: '5.7'
  - '5.6':
      php-version-tag: '5.6'
      use-with-redaxo-version-tag: '5.7'
  - '5.5':
      php-version-tag: '5.5'
      use-with-redaxo-version-tag: '5.7'
