version: "3"
services:

  redaxo:
    image: friendsofredaxo/redaxo:5-php8.0-rc-apache
    ports:
      - 20080:80   # web server will use port 20080 for http
    volumes:
      - ./html:/var/www/html:cached   # sync web root with local folder `html`
    depends_on:
      - db   # requires database container to be available
    environment:
      REDAXO_SERVER: http://localhost:20080
      REDAXO_SERVERNAME: "REDAXO + PHP 8"
      REDAXO_ERROR_EMAIL: mail@you.example
      REDAXO_LANG: de_de
      REDAXO_TIMEZONE: Europe/London
      REDAXO_DB_HOST: db   # database container name
      REDAXO_DB_NAME: redaxo
      REDAXO_DB_LOGIN: redaxo
      REDAXO_DB_PASSWORD: redaxo   # better not use for production!
      REDAXO_DB_CHARSET: utf8mb4
      REDAXO_ADMIN_USER: admin
      REDAXO_ADMIN_PASSWORD: admin123   # better not use for production!

  db:
    image: mysql:8
    volumes:
      - ./db:/var/lib/mysql:cached   # sync database with local folder `db`
    environment:
      MYSQL_DATABASE: redaxo
      MYSQL_USER: redaxo
      MYSQL_PASSWORD: redaxo   # better not use for production!
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'   # better not use for production!
