name: Docker

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [7.2, 7.3, 7.4]
        type: [apache, fpm-alpine, fpm]
    steps:
      - uses: actions/checkout@v2

      - name: Build Image ${{ matrix.php }}-${{ matrix.type }}
        run: |
            docker build ./php${{ matrix.php }}/${{ matrix.type }}/ -t ${{matrix.php}}-${{matix.type}}
