name: Docker

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ '8.1', '8.2' ]
        type: [ 'apache', 'fpm' ]
    steps:
      - uses: actions/checkout@v3

      - name: Build Image ${{ matrix.php }}-${{ matrix.type }}
        run: |
          docker build ./php${{ matrix.php }}/${{ matrix.type }}/ -t ${{matrix.php}}-${{matrix.type}}
